add_rules("mode.debug","mode.release")
set_languages("cxx20")
includes("./../../src/common/xmake.lua")
target("_tests_final")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    --add_cugencodes("native")
    --add_cugencodes("compute_61")
    add_cuflags("--extended-lambda")
    add_cuflags("-Xcompiler /openmp")
    add_deps("common")
