add_requires("eigen >=3.4.0")
add_requires("fmt >=8.1.1")
add_requires("nlohmann_json >=3.10.5")
add_requires("boost >=1.78.0")
add_requires("opengl")
add_requires("freeglut")
add_requires("glew")
add_requires("cuda", {system=true, configs={utils={"cublas","cusparse","cusolver"}}})
target("common")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_cuflags("--extended-lambda")
    add_cuflags("-Xcompiler /openmp")
    add_includedirs(".",{public=true})
    add_packages("cuda",{public=true})
    add_packages("eigen",{public=true})
    add_packages("fmt",{public=true})
    add_packages("nlohmann_json",{public=true})
    add_packages("boost",{public=true})
    add_packages("opengl",{public=true})
    add_packages("freeglut",{public=true})
    add_packages("glew",{public=true})